services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=payment
      - POSTGRES_USER=capco
      - POSTGRES_PASSWORD=capco
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql

volumes:
  db_data: